version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: posts_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: posts_db
      POSTGRES_USER: posts_user
      POSTGRES_PASSWORD: posts_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - posts_network

  # Go приложение
  app:
    build: .
    container_name: posts_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=posts_user
      - DB_PASSWORD=posts_password
      - DB_NAME=posts_db
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - posts_network

volumes:
  postgres_data:

networks:
  posts_network:
    driver: bridge
